// <auto-generated />
using System;
using EntregasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntregasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510055532_AddPreselectedWinners")]
    partial class AddPreselectedWinners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntregasApi.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultShippingCost")
                        .HasColumnType("numeric");

                    b.Property<int>("LinkExpirationHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultShippingCost = 60m,
                            LinkExpirationHours = 72
                        });
                });

            modelBuilder.Entity("EntregasApi.Models.CashRegisterSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalCashActual")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FinalCashExpected")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("InitialCash")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CashRegisterSessions");
                });

            modelBuilder.Entity("EntregasApi.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryRouteId")
                        .HasColumnType("integer");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("DeliveryRouteId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EntregasApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryInstructions")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("integer");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EntregasApi.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryRouteId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRouteId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("EntregasApi.Models.DeliveryEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("DeliveryEvidences");
                });

            modelBuilder.Entity("EntregasApi.Models.DeliveryRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DriverToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverToken")
                        .IsUnique();

                    b.ToTable("DeliveryRoutes");
                });

            modelBuilder.Entity("EntregasApi.Models.DriverExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryRouteId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("EvidencePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DeliveryRouteId");

                    b.ToTable("DriverExpenses");
                });

            modelBuilder.Entity("EntregasApi.Models.FcmToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DriverRouteToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("driver");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DriverRouteToken");

                    b.HasIndex("Role");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("FcmTokens", (string)null);
                });

            modelBuilder.Entity("EntregasApi.Models.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SalesPeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("SalesPeriodId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("EntregasApi.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("EntregasApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("AdvancePayment")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AlternativeAddress")
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryInstructions")
                        .HasColumnType("text");

                    b.Property<int?>("DeliveryRouteId")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryTime")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFullyLoaded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullyPacked")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PickupDate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PostponedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostponedNote")
                        .HasColumnType("text");

                    b.Property<int?>("SalesPeriodId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TotalPackages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("DeliveryRouteId");

                    b.HasIndex("SalesPeriodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EntregasApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EntregasApi.Models.OrderPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("QrCodeValue")
                        .IsUnique();

                    b.ToTable("OrderPackages");
                });

            modelBuilder.Entity("EntregasApi.Models.OrderPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("CashRegisterSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CashRegisterSessionId");

                    b.HasIndex("Date");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("EntregasApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntregasApi.Models.PushSubscriptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DriverRouteToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("client");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("Role", "ClientId")
                        .HasDatabaseName("IX_PushSub_Role_ClientId");

                    b.HasIndex("Role", "DriverRouteToken")
                        .HasDatabaseName("IX_PushSub_Role_DriverToken");

                    b.ToTable("PushSubscriptions", (string)null);
                });

            modelBuilder.Entity("EntregasApi.Models.Raffle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnimationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("animation_type");

                    b.Property<DateTime?>("AnnouncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("announced_at");

                    b.Property<bool>("AutoDraw")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_draw");

                    b.Property<string>("ClientSegmentFilter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_segment_filter");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateRangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_range_end");

                    b.Property<DateTime?>("DateRangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_range_start");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EligibilityRule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eligibility_rule");

                    b.Property<bool>("ExcludeBlacklisted")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_blacklisted");

                    b.Property<string>("ExcludedClientIds")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("excluded_client_ids");

                    b.Property<bool>("FrequentClientsOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("frequent_clients_only");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int?>("MaxEntriesPerClient")
                        .HasColumnType("integer")
                        .HasColumnName("max_entries_per_client");

                    b.Property<decimal?>("MinLifetimeSpent")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("min_lifetime_spent");

                    b.Property<decimal?>("MinOrderTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("min_order_total");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<bool>("NewClientsOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("new_clients_only");

                    b.Property<string>("NotificationChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_channel");

                    b.Property<bool>("NotifyWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_winner");

                    b.Property<string>("PreselectedWinnerIds")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preselected_winner_ids");

                    b.Property<string>("PrizeCurrency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prize_currency");

                    b.Property<string>("PrizeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("prize_description");

                    b.Property<Guid?>("PrizeProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("prize_product_id");

                    b.Property<string>("PrizeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prize_type");

                    b.Property<decimal?>("PrizeValue")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("prize_value");

                    b.Property<DateTime>("RaffleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raffle_date");

                    b.Property<int>("RequiredPurchases")
                        .HasColumnType("integer")
                        .HasColumnName("required_purchases");

                    b.Property<bool>("ShuffleTandaTurns")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_tanda_turns");

                    b.Property<string>("SocialBgColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("social_bg_color");

                    b.Property<string>("SocialShareImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("social_share_image_url");

                    b.Property<string>("SocialTemplate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("social_template");

                    b.Property<string>("SocialTextColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("social_text_color");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tanda_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VipOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("vip_only");

                    b.Property<int>("WinnerCount")
                        .HasColumnType("integer")
                        .HasColumnName("winner_count");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.Property<string>("WinnerMessageTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("winner_message_template");

                    b.HasKey("Id");

                    b.HasIndex("PrizeProductId");

                    b.HasIndex("RaffleDate");

                    b.HasIndex("Status");

                    b.HasIndex("TandaId");

                    b.HasIndex("WinnerId");

                    b.ToTable("raffles");
                });

            modelBuilder.Entity("EntregasApi.Models.RaffleDraw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draw_date");

                    b.Property<bool>("IsTandaShuffle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tanda_shuffle");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RaffleId")
                        .HasColumnType("uuid")
                        .HasColumnName("raffle_id");

                    b.Property<string>("SelectionMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selection_method");

                    b.Property<int?>("TandaTurnsReshuffled")
                        .HasColumnType("integer")
                        .HasColumnName("tanda_turns_reshuffled");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("DrawDate");

                    b.HasIndex("RaffleId");

                    b.HasIndex("WinnerId");

                    b.ToTable("raffle_draws");
                });

            modelBuilder.Entity("EntregasApi.Models.RaffleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<Guid>("RaffleId")
                        .HasColumnType("uuid")
                        .HasColumnName("raffle_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrderId");

                    b.HasIndex("RaffleId", "ClientId");

                    b.ToTable("raffle_entries");
                });

            modelBuilder.Entity("EntregasApi.Models.RaffleParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AssignedTandaTurn")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_tanda_turn");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_winner");

                    b.Property<string>("NotificationChannelUsed")
                        .HasColumnType("text")
                        .HasColumnName("notification_channel_used");

                    b.Property<bool>("Notified")
                        .HasColumnType("boolean")
                        .HasColumnName("notified");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<int?>("PreviousTandaTurn")
                        .HasColumnType("integer")
                        .HasColumnName("previous_tanda_turn");

                    b.Property<DateTime>("QualificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qualification_date");

                    b.Property<int>("QualifyingOrders")
                        .HasColumnType("integer")
                        .HasColumnName("qualifying_orders");

                    b.Property<decimal?>("QualifyingTotalSpent")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("qualifying_total_spent");

                    b.Property<Guid>("RaffleId")
                        .HasColumnType("uuid")
                        .HasColumnName("raffle_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RaffleId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("IX_RaffleParticipant_Raffle_Client");

                    b.ToTable("raffle_participants");
                });

            modelBuilder.Entity("EntregasApi.Models.SalesPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("SalesPeriods");
                });

            modelBuilder.Entity("EntregasApi.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("EntregasApi.Models.Tanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("penalty_amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("total_weeks");

                    b.Property<decimal>("WeeklyAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("weekly_amount");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("tandas");
                });

            modelBuilder.Entity("EntregasApi.Models.TandaParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssignedTurn")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_turn");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delivered");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tanda_id");

                    b.Property<string>("Variant")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TandaId", "AssignedTurn")
                        .IsUnique()
                        .HasDatabaseName("IX_TandaParticipant_Tanda_Turn");

                    b.ToTable("tanda_participants");
                });

            modelBuilder.Entity("EntregasApi.Models.TandaPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<decimal>("PenaltyPaid")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("penalty_paid");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("EntregasApi.Models.TandaProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("EntregasApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntregasApi.Models.CashRegisterSession", b =>
                {
                    b.HasOne("EntregasApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntregasApi.Models.ChatMessage", b =>
                {
                    b.HasOne("EntregasApi.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntregasApi.Models.DeliveryRoute", "DeliveryRoute")
                        .WithMany("ChatMessages")
                        .HasForeignKey("DeliveryRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Delivery");

                    b.Navigation("DeliveryRoute");
                });

            modelBuilder.Entity("EntregasApi.Models.Delivery", b =>
                {
                    b.HasOne("EntregasApi.Models.DeliveryRoute", "DeliveryRoute")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("EntregasApi.Models.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryRoute");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EntregasApi.Models.DeliveryEvidence", b =>
                {
                    b.HasOne("EntregasApi.Models.Delivery", "Delivery")
                        .WithMany("Evidences")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("EntregasApi.Models.DriverExpense", b =>
                {
                    b.HasOne("EntregasApi.Models.DeliveryRoute", "DeliveryRoute")
                        .WithMany()
                        .HasForeignKey("DeliveryRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryRoute");
                });

            modelBuilder.Entity("EntregasApi.Models.Investment", b =>
                {
                    b.HasOne("EntregasApi.Models.SalesPeriod", "SalesPeriod")
                        .WithMany("Investments")
                        .HasForeignKey("SalesPeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntregasApi.Models.Supplier", "Supplier")
                        .WithMany("Investments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesPeriod");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("EntregasApi.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("EntregasApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EntregasApi.Models.Order", b =>
                {
                    b.HasOne("EntregasApi.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.DeliveryRoute", "DeliveryRoute")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryRouteId");

                    b.HasOne("EntregasApi.Models.SalesPeriod", "SalesPeriod")
                        .WithMany("Orders")
                        .HasForeignKey("SalesPeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("DeliveryRoute");

                    b.Navigation("SalesPeriod");
                });

            modelBuilder.Entity("EntregasApi.Models.OrderItem", b =>
                {
                    b.HasOne("EntregasApi.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntregasApi.Models.OrderPackage", b =>
                {
                    b.HasOne("EntregasApi.Models.Order", "Order")
                        .WithMany("Packages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EntregasApi.Models.OrderPayment", b =>
                {
                    b.HasOne("EntregasApi.Models.CashRegisterSession", "CashRegisterSession")
                        .WithMany("Payments")
                        .HasForeignKey("CashRegisterSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntregasApi.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegisterSession");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EntregasApi.Models.Raffle", b =>
                {
                    b.HasOne("EntregasApi.Models.TandaProduct", "PrizeProduct")
                        .WithMany()
                        .HasForeignKey("PrizeProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntregasApi.Models.Tanda", "Tanda")
                        .WithMany()
                        .HasForeignKey("TandaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntregasApi.Models.Client", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrizeProduct");

                    b.Navigation("Tanda");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("EntregasApi.Models.RaffleDraw", b =>
                {
                    b.HasOne("EntregasApi.Models.Raffle", "Raffle")
                        .WithMany("Draws")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Client", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Raffle");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("EntregasApi.Models.RaffleEntry", b =>
                {
                    b.HasOne("EntregasApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Raffle", "Raffle")
                        .WithMany("Entries")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Order");

                    b.Navigation("Raffle");
                });

            modelBuilder.Entity("EntregasApi.Models.RaffleParticipant", b =>
                {
                    b.HasOne("EntregasApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Raffle", "Raffle")
                        .WithMany("Participants")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Raffle");
                });

            modelBuilder.Entity("EntregasApi.Models.Tanda", b =>
                {
                    b.HasOne("EntregasApi.Models.TandaProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntregasApi.Models.TandaParticipant", b =>
                {
                    b.HasOne("EntregasApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregasApi.Models.Tanda", "Tanda")
                        .WithMany("Participants")
                        .HasForeignKey("TandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tanda");
                });

            modelBuilder.Entity("EntregasApi.Models.TandaPayment", b =>
                {
                    b.HasOne("EntregasApi.Models.TandaParticipant", "Participant")
                        .WithMany("Payments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("EntregasApi.Models.CashRegisterSession", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EntregasApi.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EntregasApi.Models.Delivery", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("EntregasApi.Models.DeliveryRoute", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Deliveries");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EntregasApi.Models.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Items");

                    b.Navigation("Packages");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EntregasApi.Models.Raffle", b =>
                {
                    b.Navigation("Draws");

                    b.Navigation("Entries");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EntregasApi.Models.SalesPeriod", b =>
                {
                    b.Navigation("Investments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EntregasApi.Models.Supplier", b =>
                {
                    b.Navigation("Investments");
                });

            modelBuilder.Entity("EntregasApi.Models.Tanda", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EntregasApi.Models.TandaParticipant", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
