// <auto-generated />
using EntregasApi.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace EntregasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AddMissingOrderScheduledDeliveryDateColumn
    {
    }
}
